name: Ksu
on:
  workflow_dispatch:

jobs:
  ci-test:
    name: ci-ksu
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Ksu CI
      uses: ./
      with:
          kernel-url: https://github.com/Fyg369/mcd_kernel_oneplus_sdm845
          kernel-dir: ksu
          kernel-branch: mcd-OOS-R
          config: mcd_ksu_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r416183b
          #extra-cmd: KCFLAGS="-std=gnu99"
          ksu: true
          ksu-version: legacy
          ksu-other: true
          ksu-url: https://github.com/KernelSU-Next/KernelSU-Next
          lxc: true
          lxc-patch: true
          nethunter: true
          nethunter-patch: true
          bbrplus: true
          zram: true
          bbg: true
          anykernel3: true
